// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2003.Models;

#nullable disable

namespace _2003.Migrations
{
    [DbContext(typeof(Comp2003Context))]
    [Migration("20230126104806_AddComments")]
    partial class AddComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2003.Models.Evaluator", b =>
                {
                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int")
                        .HasColumnName("evaluatorID");

                    b.Property<string>("EvaluatorName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("evaluator_name");

                    b.HasKey("EvaluatorId")
                        .HasName("PK__Evaluato__B05254E9143CD590");

                    b.ToTable("Evaluator", (string)null);
                });

            modelBuilder.Entity("_2003.Models.Img", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Breadth")
                        .HasColumnType("int")
                        .HasColumnName("breadth");

                    b.Property<int?>("ChildAge")
                        .HasColumnType("int")
                        .HasColumnName("child_age");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Depth")
                        .HasColumnType("int")
                        .HasColumnName("depth");

                    b.Property<int?>("EvaluatorId")
                        .HasColumnType("int")
                        .HasColumnName("evaluatorID");

                    b.Property<int?>("Extent")
                        .HasColumnType("int")
                        .HasColumnName("extent");

                    b.Property<DateTime?>("ImgDate")
                        .HasColumnType("date")
                        .HasColumnName("img_date");

                    b.Property<string>("ImgEvent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("img_event");

                    b.Property<byte[]>("Picture")
                        .HasColumnType("image")
                        .HasColumnName("picture");

                    b.HasKey("Id")
                        .HasName("PK__img__3213E83FA8C7B3CA");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("img", (string)null);
                });

            modelBuilder.Entity("_2003.Models.Img", b =>
                {
                    b.HasOne("_2003.Models.Evaluator", "Evaluator")
                        .WithMany("Imgs")
                        .HasForeignKey("EvaluatorId")
                        .HasConstraintName("FK_PersonOrder");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("_2003.Models.Evaluator", b =>
                {
                    b.Navigation("Imgs");
                });
#pragma warning restore 612, 618
        }
    }
}
